[2024-11-16T13:14:51.031+0000] {processor.py:186} INFO - Started process (PID=2564) to work on /opt/airflow/dags/lab9.py
[2024-11-16T13:14:51.031+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lab9.py for tasks to queue
[2024-11-16T13:14:51.033+0000] {logging_mixin.py:190} INFO - [2024-11-16T13:14:51.032+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lab9.py
[2024-11-16T13:14:51.048+0000] {logging_mixin.py:190} INFO - [2024-11-16T13:14:51.046+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lab9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lab9.py", line 7, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-11-16T13:14:51.050+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lab9.py
[2024-11-16T13:14:51.063+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lab9.py took 0.037 seconds
[2024-11-16T13:15:21.241+0000] {processor.py:186} INFO - Started process (PID=2627) to work on /opt/airflow/dags/lab9.py
[2024-11-16T13:15:21.241+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lab9.py for tasks to queue
[2024-11-16T13:15:21.242+0000] {logging_mixin.py:190} INFO - [2024-11-16T13:15:21.242+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lab9.py
[2024-11-16T13:15:21.254+0000] {logging_mixin.py:190} INFO - [2024-11-16T13:15:21.251+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lab9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lab9.py", line 7, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-11-16T13:15:21.255+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lab9.py
[2024-11-16T13:15:21.268+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lab9.py took 0.032 seconds
[2024-11-16T13:15:51.935+0000] {processor.py:186} INFO - Started process (PID=2690) to work on /opt/airflow/dags/lab9.py
[2024-11-16T13:15:51.936+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lab9.py for tasks to queue
[2024-11-16T13:15:51.937+0000] {logging_mixin.py:190} INFO - [2024-11-16T13:15:51.937+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lab9.py
[2024-11-16T13:15:51.951+0000] {logging_mixin.py:190} INFO - [2024-11-16T13:15:51.948+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lab9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lab9.py", line 7, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-11-16T13:15:51.952+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lab9.py
[2024-11-16T13:15:51.967+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lab9.py took 0.037 seconds
[2024-11-16T13:16:22.422+0000] {processor.py:186} INFO - Started process (PID=2753) to work on /opt/airflow/dags/lab9.py
[2024-11-16T13:16:22.423+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lab9.py for tasks to queue
[2024-11-16T13:16:22.424+0000] {logging_mixin.py:190} INFO - [2024-11-16T13:16:22.423+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lab9.py
[2024-11-16T13:16:22.436+0000] {logging_mixin.py:190} INFO - [2024-11-16T13:16:22.433+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lab9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lab9.py", line 7, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-11-16T13:16:22.437+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lab9.py
[2024-11-16T13:16:22.452+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lab9.py took 0.035 seconds
[2024-11-16T13:16:53.090+0000] {processor.py:186} INFO - Started process (PID=2816) to work on /opt/airflow/dags/lab9.py
[2024-11-16T13:16:53.091+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lab9.py for tasks to queue
[2024-11-16T13:16:53.092+0000] {logging_mixin.py:190} INFO - [2024-11-16T13:16:53.092+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lab9.py
[2024-11-16T13:16:53.103+0000] {logging_mixin.py:190} INFO - [2024-11-16T13:16:53.100+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lab9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lab9.py", line 7, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-11-16T13:16:53.104+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lab9.py
[2024-11-16T13:16:53.128+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lab9.py took 0.042 seconds
[2024-11-16T13:17:23.583+0000] {processor.py:186} INFO - Started process (PID=2879) to work on /opt/airflow/dags/lab9.py
[2024-11-16T13:17:23.584+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lab9.py for tasks to queue
[2024-11-16T13:17:23.585+0000] {logging_mixin.py:190} INFO - [2024-11-16T13:17:23.584+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lab9.py
[2024-11-16T13:17:23.596+0000] {logging_mixin.py:190} INFO - [2024-11-16T13:17:23.594+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lab9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lab9.py", line 7, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-11-16T13:17:23.597+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lab9.py
[2024-11-16T13:17:23.616+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lab9.py took 0.038 seconds
[2024-11-16T13:17:53.825+0000] {processor.py:186} INFO - Started process (PID=2943) to work on /opt/airflow/dags/lab9.py
[2024-11-16T13:17:53.826+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/lab9.py for tasks to queue
[2024-11-16T13:17:53.827+0000] {logging_mixin.py:190} INFO - [2024-11-16T13:17:53.827+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/lab9.py
[2024-11-16T13:17:53.838+0000] {logging_mixin.py:190} INFO - [2024-11-16T13:17:53.836+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/lab9.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/lab9.py", line 7, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
[2024-11-16T13:17:53.839+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/lab9.py
[2024-11-16T13:17:53.855+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/lab9.py took 0.034 seconds
